//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuan_13.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public SinhVien()
        {
            this.KetQua = new HashSet<KetQua>();
        }
    
        public string MaSinhVien { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string MaLop { get; set; }
    
        public virtual ICollection<KetQua> KetQua { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
